[project]
name = "llm-knowledge-enhancement"
version = "0.1.0"
description = "Recommendation system for course NLP at FINKI"
readme = "README.md"
authors = [
    { name = "viki123v", email = "viktorhristovski629@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
main = "llm_knowledge_enhancement:main"

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "prek>=0.3.9",
    "ruff>=0.15.11",
]

[tool.ruff.lint]
extend-select = ["I"]
